// <auto-generated />
using Boltway.Storage.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boltway.Storage.Sqlite.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260810111621_AddRealm")]
    partial class AddRealm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.AuthorizationCodeRow", b =>
                {
                    b.Property<byte[]>("CodeHash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("code_hash");

                    b.Property<long>("AuthTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auth_time");

                    b.Property<int>("ChallengeMethod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("challenge_method");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<int>("ClientIdKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id_kind");

                    b.Property<string>("CodeChallenge")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_challenge");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<string>("GrantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("grant_id");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued_at");

                    b.Property<string>("Nonce")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("nonce");

                    b.Property<bool>("PkceWasRequested")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkce_was_requested");

                    b.Property<long?>("RedeemedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("RedirectUriUsed")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("redirect_uri_used");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("resources");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.HasKey("CodeHash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_authorization_codes_expires_at");

                    b.ToTable("authorization_codes", (string)null);
                });

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.ConsentRow", b =>
                {
                    b.Property<string>("Subject")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<string>("ClientId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<int>("ClientIdKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id_kind");

                    b.Property<long>("GrantedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("granted_at");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("resources");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.HasKey("Subject", "ClientId");

                    b.ToTable("consents", (string)null);
                });

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.ExternalLoginRow", b =>
                {
                    b.Property<string>("Realm")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("default")
                        .HasColumnName("realm");

                    b.Property<string>("UpstreamIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("upstream_issuer");

                    b.Property<string>("UpstreamSubject")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("upstream_subject");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("Realm", "UpstreamIssuer", "UpstreamSubject");

                    b.HasIndex("Subject")
                        .HasDatabaseName("ix_external_logins_subject");

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.GrantRow", b =>
                {
                    b.Property<string>("GrantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("grant_id");

                    b.Property<long>("AuthTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auth_time");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<int>("ClientIdKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id_kind");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("resources");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("GrantId");

                    b.ToTable("grants", (string)null);
                });

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.RefreshTokenFamilyRow", b =>
                {
                    b.Property<string>("FamilyId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("family_id");

                    b.Property<long>("RevokedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked_at");

                    b.HasKey("FamilyId");

                    b.ToTable("refresh_token_families", (string)null);
                });

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.RefreshTokenRow", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("token_hash");

                    b.Property<long?>("ConsumedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consumed_at");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("family_id");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<string>("GrantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("grant_id");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued_at");

                    b.Property<byte[]>("PredecessorHash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("predecessor_hash");

                    b.Property<byte[]>("SuccessorHash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("successor_hash");

                    b.HasKey("TokenHash");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.UserRow", b =>
                {
                    b.Property<string>("Subject")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<long?>("DisabledAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_verified");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("default")
                        .HasColumnName("realm");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Subject");

                    b.HasIndex("Realm", "NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_users_realm_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Boltway.Storage.EntityFrameworkCore.Entities.ExternalLoginRow", b =>
                {
                    b.HasOne("Boltway.Storage.EntityFrameworkCore.Entities.UserRow", null)
                        .WithMany()
                        .HasForeignKey("Subject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
